name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:
    runs-on: windows-latest
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: msbuild version check
      run: msbuild --version
