name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:

    runs-on: windows-latest
    env:
      PATH: "${env:PATH};C:\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin"
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Run MSBuild
      shell: pwsh
      run: msbuild .\MFCApplication1\MFCApplication1.sln
      
    - name: Run Google Test
      run: .\MFCApplication1\x64\Release\MyGoogleTest1.exe --gtest_output=xml:MyTestResult001.xml
