name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:
    runs-on: windows-latest
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: msbuild version check
      run: msbuild --version
    - name: run msbuild
      run: msbuild .\MFCApplication1\MFCApplication1.sln
      
    - name: run google test
      run: .\MFCApplication1\x64\Release\MyGoogleTest1.exe --gtest_output=xml:C:\\Users\\Modi\\MyTestResult001.xml
