name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:

    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Check Path
      run: echo PATH
      
    - name: Run Google Test
      run: .\MFCApplication1\x64\Release\MyGoogleTest1.exe --gtest_output=xml:MyTestResult001.xml
