name: Modi_Workflow_2

on: [ push ]
jobs:
  ModiClangTest:
    runs-on: windows-latest
    steps:
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
    - name: Test Printing
      run: echo "Hello World"
