name: Modi_Workflow_1

on: [ push, pull_request ]

jobs:
  myBuild:
    runs-on: Windows
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo "Hello, Modi World!"
      
    - name: Run a multi-line script
      run: |
        echo "Add other actions to build"
        echo "test, and deploy your project."
