name: Modi_Workflow_1

on: [ push, pull_request ]

jobs:
  myBuild:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run MSBuild
      run: msbuild .\MFCApplication1\MFCApplication1.sln
      
    - name: Run Google Test
      run: .\MFCApplication1\x64\Release\MyGoogleTest1.exe --gtest_output=xml:MyTestResult001.xml
