name: Modi_Workflow_1

on: [ push, pull_request ]
jobs:
  myBuild:
    runs-on: windows-latest
    steps:
    - name: setup-actions
      uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: msbuild version check
      run: msbuild --version
      
    - name: nuget version check
      run: nuget help
    
    - name: run msbuild
      run: msbuild .\MFCApplication1\MFCApplication1.sln /property:Configuration=Release /property:Platform=x64
      
    - name: run google test
      run: .\MFCApplication1\x64\Release\MyGoogleTest1.exe --gtest_output=xml:C:\\Users\\Modi\\MyTestResult001.xml
